rust-mobile/cargo-subcommand

src/utils.rs
Multilevel cargo workspace members are always written with a forward
slash, for example:
[workspace]
members = [
"apps/android-app",
]
On Windows forward slashes are not accepted at all, not even
fs::canonicalize() is able to normalize them. Calling that function or
trying to read a file from a path containing this string results in the
following error:
Error: The filename, directory name, or volume label syntax is
incorrect. (os error 123)
Splitting the member name on a forward slash and constructing a new
PathBuf from the parts seems the easiest to get a properly normalized
path with the right separator for the platform.
---
Perhaps this line should be scoped by `#[cfg(windows)]` but I rather keep it generic. I initally expected `PathBuf` to have a `.extend()` method accepting an …
=> utils: Normalize slashes in multilevel workspace members on Windows

Cargo.lock, Cargo.toml, src/error.rs, src/lib.rs, src/subcommand.rs, src/utils.rs
Fix issue where e.g. wildcards result in Err that is unwrapped by the calling function, resulting an unnecessary build fail as the target fall through is unused.
This popped up when trying to build Bevy (with winit) for Android. It wasn't clear to me that this is the right place to address the issue, for instance it could instead be handled at the calling function's unwrap. In this case the early return also precludes checking following members, so this felt the the nicer way to cleanup given the crate is using a lot of unwraps and removing one wouldn't have put much a dent in it.
=> Fix build error when wildcard used in workspace.

src/utils.rs
Workspace members (globs) should be discovered from the directory containing `Cargo.toml` with these workspaces, not from the directory the user happens to in.
Take for example android-ndk-rs. When cd'd into `ndk-examples` this would find the root manifest file in `../Cargo.toml`, but try to glob in the current directory - `ndk-examples` - where it's obviously not going to find another `ndk-examples` containing `Cargo.toml`. The `Subcommand` constructor hence considers this package as not being in a workspace and emits `target_dir` at `ndk-examples/target`. This fails later in the build when files cannot be found in the toplevel `target/` dir.
Fixes https://github.com/rust-windowing/android-ndk-rs/issues/105
=> utils: Search for workspace members relative to root manifest

src/subcommand.rs
If this environment variable is set it should be used over the current or workspace directory.
Fixes: https://github.com/rust-windowing/android-ndk-rs/issues/102
=> subcommand: Listen to CARGO_(BUILD_)TARGET_DIR over cwd

src/subcommand.rs, src/utils.rs
Canonicalization requires the path to exist such that the OS can resolve symlinks. The `target/` folder doesn't exist in a clean build environment (ie. after cloning or running `cargo clean`), causing the unwrap to panic.
The same logic is applied to paths coming from `--target-dir` which may or may not be relative. Paths from `find_workspace` (based on those from `find_package`) are already canonicalized, however.
Tested normal `cargo apk` invocation with and without `target/` dir, and `CARGO_TARGET_DIR` with relative and absolute path.
Fixes: bec3883 ("subcommand: Listen to CARGO_(BUILD_)TARGET_DIR over cwd (#4)")
=> subcommand: Do not canonicalize `target/` path that may not exist

Cargo.lock, Cargo.toml, src/utils.rs
We recently taught `fn member()` to look for Cargo.toml files in
workspace members (globs) relative to the workspace root (the directory
containing Cargo.toml with the `[workspace]` listing of these members).
This means the path to the workspace root is now concatenated to the
glob path before searching, which didn't happen before.  That path
happens to be canonicalized just at the top of `fn find_package()`
consequently the whole thing falls apart when Windows UNC paths are used
in places they aren't supported, like `glob`.  No paths are returned,
the package isn't found (`Error::ManifestNotFound` below) and
`cargo-apk` is once again broken on Windows.
We have already been discussing to add `dunce`, now is the right time to
get rid of UNC paths in `cargo-submodule` once and for all. …
=> utils: Strip UNC from canonicalized path which is not supported by glob

src/subcommand.rs
Looks like I found new a new use case for `cargo-subcommand` :)
=> Don't read args in cargo-subcommand.

src/config.rs, src/error.rs, src/lib.rs, src/subcommand.rs, src/utils.rs
Read config from .cargo/config.toml
Fix an error where the target directory was hard coded, causing problems when a different target directory was used.
https://github.com/rust-windowing/android-ndk-rs/issues/102
=> Read target-dir from cargo config file

src/subcommand.rs
Makes the current code shippable. This way the initial release my subcommands is not blocked on a rewrite of argument parsing.
=> Fix separator handling in argument parsing

src/config.rs, src/error.rs, src/manifest.rs, src/utils.rs
While implementing #12 an invalid `.cargo/config.toml` turned into an undescriptive and incorrect `ManifestNotFound` here.  Forwarding the parsing error gives the user a much more descriptive error message that'll help understand what to fix.
=> error: Include file paths as error context; distinguish toml parsing errors from "manifest not found"

.github/workflows/rust.yaml, src/subcommand.rs
Let GH CI help us check formatting, clippy, the few tests that we have and build-test the documentation.
=> ci: Inherit simplified GitHub Actions CI script from android-ndk

src/config.rs, src/lib.rs, src/subcommand.rs, src/utils.rs
Environment variables can be set and optionally override the process environment through `.cargo/config.toml`'s `[env]` section: https://doc.rust-lang.org/cargo/reference/config.html#env
These config variables have specific precedence rules with regards to overriding the environment set in the process, and can optionally represent paths relative to the parent of the containing `.cargo/` folder.
=> config: Read environment variables from `[env]` section in `config.toml`

src/config.rs, src/error.rs, src/subcommand.rs, src/utils.rs
Leaving the caller to read and merge config environment values with the process environment is not only cumbersome as seen in [rust-windowing/android-ndk-rs#233], but these values need to be propagated into the process environment anyway to be usable by any subprocess spawned by the caller (ie. `cargo-apk` spawning `cargo rustc`, which can internally spawn a bunch of compilers and linkers too).
Instead, do this automatically when the caller invokes `Subcommand::new` while still leaving the door open for crates to read the environment from the public `subcommand.manifest.env` member.
[rust-windowing/android-ndk-rs#233]: https://github.com/rust-windowing/android-ndk-rs/pull/233
=> Propagate `.cargo/config.toml` `[env]` settings to the process environment

src/subcommand.rs
Strangely enough I added this call at a random place in `Subcommand::new()`, instead of considering that it was both:
1. Breaking the logic for deducing `target_dir` in two separated blocks;
2. Preventing the first block - which reads environment variables! - from seeing what was configured in `.cargo/config.toml` through `[env]`.
Fix this by moving the call straight after identifying the root directory for the selected package.
=> subcommand: Parse and propagate `[env]` vars at the earliest possible moment

src/config.rs, src/error.rs, src/manifest.rs, src/subcommand.rs, src/utils.rs
When running `cargo-subcommand` without `-p` package selection against a workspace currently only the first found package is returned.  This should be implemented over time to return all packages (and artifacts adhering to target selection), but return a more specific error for the time being instead of making it seem like there's only one package.
=> manifest: Be more specific about not supporting multiple packages yet

Cargo.toml, src/subcommand.rs
Use the `current_platform` crate for zero-cost platform detection. Shaves off 90ms off subcommand startup on my machine (invoking rustc is slow when it's managed by rustup).
The `Error::RustcNotFound` variant is now never constructed, but I didn't remove it because that would be a semver-breaking change. Likewise with the superfluous `.to_owned()` - not changed to avoid an API break.
Fixes #19
=> Do not call rustc for platform detection; use `current_platform` instead

src/error.rs, src/subcommand.rs, src/utils.rs
When `cargo` scans for a workspace it simply walks up the directories until finding the first `Cargo.toml` with a `[workspace]` declaration.  All crates are detected relative to this, and no special skipping behaviour (walking further up the directories) occurs when a package was not found (was previously happening in `find_package()+member()`).
Simplify the original code somewhat by making this feat more obvious, rejecting more invalid configurations.
=> Linearize workspace detection

src/manifest.rs, src/subcommand.rs, src/utils.rs
Depends on #23
Especially with the new `[workspace.package]` values, `cargo-apk` would like to know the path of the workspace that was found for the requested package, so that `cargo-apk` can scan it for values to inherit.
=> Provide workspace manifest path in `Subcommand`

Cargo.toml, README.md, src/args.rs, src/artifact.rs, src/error.rs, src/lib.rs, src/manifest.rs, src/subcommand.rs, src/utils.rs
Fixes https://github.com/rust-mobile/cargo-apk/issues/7
@dvc94ch this WIP PR pulls the lib rename changes out of #15 and expands it with similar changes for `[[bin]]` and supporting `autobins=false`.  We'll have to rework what `Artifact`s to return to the user given that by default the library _and all binary targets_ are built: https://doc.rust-lang.org/cargo/commands/cargo-build.html#target-selection.  This is different for `cargo run` which only picks one binary target (I think from the shared pool of `src/main.rs`, `src/bin/*`, _and_ any other file specified through `[[bin]]`) and otherwise errors out.
At the same time I'm thinking about renaming `Root` to `Lib` and `Bin` or otherwise passing such information, so that a caller like `cargo-apk` knows what it builds (and error …
=> Support `autobins` and target renaming `[lib]` and `[[bin]]`

src/error.rs, src/subcommand.rs
The reported error and suggestion is completely incorrect when trying to run an example that doesn't exist.
=> Add separate `ExampleNotFound` `Error` instead of mis-using `BinNotFound`

src/manifest.rs
Fixes https://github.com/rust-mobile/cargo-subcommand/issues/29
If globs provided in the `members` array resolve to files, even if none of its results are (symlinks to) directories or if the path is a relative path to a file without any globbing directives, `cargo` skips it without error.  Cargo only errors out if the glob (or again relative path) didn't resolve to any files at all (which is what `glob::glob()` should also be doing for us).
It does however support symlinks, meaning we need to canonicalize every result to follow any symlinks before deducing if the entry is a directory that needs to be treated as a workspace member crate.
=> manifest: Skip non-directories when resolving workspace `members`
